# Generated by Django 4.1.3 on 2022-11-26 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('detail', models.CharField(max_length=125, verbose_name='通知详情')),
                ('putTime', models.CharField(db_column='put_time', max_length=10, verbose_name='通知时间')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('name', models.CharField(max_length=32, verbose_name='科室名称')),
                ('detail', models.CharField(max_length=125, verbose_name='通知详情')),
                ('putTime', models.CharField(db_column='put_time', max_length=10, verbose_name='通知时间')),
            ],
            options={
                'db_table': 'offices',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('userName', models.CharField(db_column='user_name', max_length=32, verbose_name='用户账号')),
                ('passWord', models.CharField(db_column='pass_word', max_length=32, verbose_name='用户密码')),
                ('name', models.CharField(max_length=20, verbose_name='用户姓名')),
                ('gender', models.CharField(max_length=2, verbose_name='用户性别')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('createTime', models.CharField(db_column='create_time', max_length=19, verbose_name='添加时间')),
                ('type', models.IntegerField(verbose_name='用户身份')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('user', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users')),
                ('record', models.CharField(max_length=32, verbose_name='医师学历')),
                ('job', models.CharField(max_length=20, verbose_name='医师职称')),
                ('good', models.CharField(max_length=125, verbose_name='专长描述')),
                ('total', models.FloatField(verbose_name='挂号费用')),
                ('office', models.ForeignKey(db_column='office_id', on_delete=django.db.models.deletion.CASCADE, to='app.offices')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('user', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.users')),
                ('address', models.CharField(max_length=64, verbose_name='联系地址')),
                ('card', models.CharField(max_length=18, verbose_name='身份证号')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='RegisteLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='记录编号')),
                ('registeTime', models.CharField(db_column='registe_time', max_length=10, verbose_name='预约时间')),
                ('createTime', models.CharField(db_column='create_time', max_length=10, verbose_name='提交时间')),
                ('total', models.FloatField(verbose_name='挂号费用')),
                ('status', models.IntegerField(verbose_name='挂号状态')),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='app.doctors')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, to='app.patients')),
            ],
            options={
                'db_table': 'registe_logs',
            },
        ),
    ]
